version: '3'
services:
  db:
    build:
      context: mssql-server
      args:
        - BASE_IMAGE=${DATABASE_IMAGE}
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=d5RxC2Vt@3g9R
    ports:
      - 1433:1433
    hostname: db
  notebook:
    build:
      context: ../containers/generic-notebook
      args:
        - BASE_IMAGE=${NOTEBOOK_IMAGE}
    environment:
      - JUPYTER_TOKEN=foo123
      - MSSQL_SA_PASSWORD=d5RxC2Vt@3g9R
    ports:
      - 8888:8888
    depends_on:
      - db
    volumes:
      - ./notebooks/Test.ipynb:/home/jovyan/Test.ipynb
