version: '3'
services:
  db:
    build: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=d5RxC2Vt@3g9R
    ports:
      - 1433:1433
    hostname: db
  notebook:
    build: ../tensorflow-notebook
    environment:
      - JUPYTER_TOKEN=
      - MSSQL_SA_PASSWORD=d5RxC2Vt@3g9R
    ports:
      - 8888:8888
    depends_on:
      - db
    volumes:
      - ./notebooks:/home/jovyan
