apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: notebook
  name: notebook
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: notebook
    spec:
      containers:
      - env:
        - name: JUPYTER_TOKEN
        - name: MSSQL_SA_PASSWORD
          value: d5RxC2Vt@3g9R
        image: notebook
        name: notebook
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /home/jovyan
          name: notebook-claim0
      restartPolicy: Always
      volumes:
      - name: notebook-claim0
        persistentVolumeClaim:
          claimName: notebook-claim0
status: {}
