name: Build and publish containers
on:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches:
      - 'main'
jobs:
  smoketest:
    uses: ./.github/workflows/smoketest.yml
  build_and_publish:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#nobuild') }}
    strategy:
      fail-fast: true
      matrix:
        base_images:
         - jupyter/minimal-notebook
         - jupyter/r-notebook
         - jupyter/scipy-notebook
         - jupyter/tensorflow-notebook
         - jupyter/datascience-notebook
         - jupyter/pyspark-noteboo
         - jupyter/all-spark-notebook
    steps:
      - name: Checkout the code from GitHub
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.base_images }}-mssql
          flavor: |
            latest=true
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
      - name: Build an image and push it to ghcr.io
        uses: docker/build-push-action@v3
        with:
          context: containers/generic-notebook
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            IMAGE_SOURCE=${{ github.repository }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

