name: Build tensorflow-notebook
on:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches:
      - 'main'
jobs:
  smoketest:
    uses: ./.github/workflows/smoketest-tensorflow-notebook.yml
  publish-container:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#nobuild') }}
    steps:
    - name: Checkout the code from GitHub
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        flavor: |
          latest=true
        tags: |
          type=raw,value={{date 'YYYYMMDD'}}
    - name: Build an image and push it to ghcr.io
      uses: docker/build-push-action@v3
      with:
        context: containers/generic-notebook
        build-args: |
          BASE_IMAGE=jupyter/tensorflow-notebook
          IMAGE_SOURCE=${{ github.repository }}
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

